In [ ]:
1. Import the numpy package under the name np
2. Print the numpy version and the configuration
3. Create a null vector of size 10
4. How to find the memory size of any array
5. How to get the documentation of the numpy add function from the command line?   ########### no idea
6. Create a null vector of size 10 but the fifth value which is 1
7. Create a vector with values ranging from 10 to 49
8. Reverse a vector (first element becomes last)
9. Create a 3x3 matrix with values ranging from 0 to 8
10. Find indices of non-zero elements from [1,2,0,0,4,0]

In [7]:
import numpy as np
np.version.version
np.show_config()

mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/roshan/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C:/Users/roshan/Anaconda3\\Library\\include']
blas_mkl_info:
    libraries = ['mkl_rt']
    library_dirs = ['C:/Users/roshan/Anaconda3\\Library\\lib']
    define_macros = [('SCIPY_MKL_H', None), ('HAVE_CBLAS', None)]
    include_dirs = ['C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\include', 'C:\\Program Files (x86)\\IntelSWTools\\compilers_and_libraries_2019.0.117\\windows\\mkl\\lib', 'C

In [31]:
#3. Create a null vector of size 10
a=[None]*10
#a.extend([]*10)
np.size(a)

10

In [12]:
a=np.array([1,2,3]) #4. How to find the memory size of any array
np.size(a)

3

In [36]:
#5. How to get the documentation of the numpy add function from the command line?
#6. Create a null vector of size 10 but the fifth value which is 1
b=[None]*10
b[4]=1
b


[None, None, None, None, 1, None, None, None, None, None]

In [73]:
#7. Create a vector with values ranging from 10 to 49
c=np.array(np.arange(10,50))
c


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [71]:
# another way using slicing
np.arange(50)[10:]


array([10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26,
       27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43,
       44, 45, 46, 47, 48, 49])

In [75]:
#. Create a 3x3 matrix with values ranging from 0 to 8
mat=np.arange(9).reshape(3,3)
mat

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [118]:
#10. Find indices of non-zero elements from [1,2,0,0,4,0]
arr=[1,2,0,0,4,0]
print("index of 1=%d \n index of 2=%d \n index of 4=%d"%(arr.index(1),arr.index(2),arr.index(4)))


#another way for any list 
print("#another way for any list  using for loop ")

for a in range(len(arr)+1):
    if(arr[a-1]!=0):
        print("index of ",arr[a-1])
        print(a-1)
    




index of 1=0 
 index of 2=1 
 index of 4=4
#another way for any list  using for loop 
index of  1
0
index of  2
1
index of  4
4


In [125]:
#another way using nonzero( ) function
arr=[1,2,0,0,4,0]
a=np.nonzero(arr)
print(a)

(array([0, 1, 4], dtype=int64),)


In [129]:
import numpy as np
0*5
0*np.nan


nan

In [137]:
np.inf>np.nan

False

In [138]:
np.nan-np.nan

nan

In [139]:
np.nan in set([np.nan])

True

In [141]:
0.3==3*0.1

False

In [154]:
#21. Create a checkerboard 8x8 matrix using the tile function
arr=np.array([[0,1],[1,0]])
np.tile(arr,(4,4))

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

In [161]:
#22. Normalize a 5x5 random matrix
arr=np.random.randn(25).reshape(5,5)
arr2=(arr-arr.mean())/np.std(arr)
print(arr)
arr2

[[ 0.23923359 -0.08700533 -0.73425728 -0.40161897 -2.01229539]
 [-1.66361949  0.10712846 -0.91935869 -0.37556398  1.12181386]
 [-1.19429221  0.44458294 -0.14632289  1.30837566  0.25694629]
 [ 0.94483538 -2.05135537 -1.29807414  1.0351552  -0.31642014]
 [-0.54244637 -2.26293871  1.16107936  0.98151573  1.16746225]]


array([[ 0.41512566,  0.11331882, -0.48546036, -0.17773337, -1.66778604],
       [-1.34522253,  0.29291391, -0.6566995 , -0.15362964,  1.23160939],
       [-0.91104322,  0.60509638,  0.05844356,  1.40419956,  0.43151186],
       [ 1.06788485, -1.70392082, -1.00705291,  1.15144062, -0.09891509],
       [-0.30801419, -1.89965865,  1.2679343 ,  1.10181822,  1.27383917]])